# Generated by Django 4.1.7 on 2023-04-12 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('composition', models.TextField(default='')),
                ('benefits', models.TextField()),
                ('category', models.CharField(choices=[('CR', 'Car'), ('WH', 'Watch'), ('SH', 'SHOES'), ('CY', 'CYCLE'), ('WL', 'Wallets'), ('BT', 'Belt'), ('SG', 'Sun-Glass'), ('TB', 'Travel-bag'), ('HP', 'Headphone')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chattogram', 'Chattogram'), ('Khulna', 'Khulna'), ('Sylhet', 'Sylhet'), ('Rajshahi', 'Rajshahi'), ('Mymensingh', 'Mymensingh'), ('Rangpur', 'Rangpur'), ('Cumilla', 'Cumilla'), ('Barishal', 'Barishal'), ('Narayanganj', 'Narayanganj'), ('Gazipur', 'Gazipur')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
